[workspace]
resolver = "2"

members = [
    "vessel-core",
]

[workspace.dependencies]
prople-did-core = {version = "~0.4"}
prople-crypto = {version = "~0.2"}
rst-common = {version = "~1", features=["with-errors"]}
rstdev-domain = {version = "~0.1"}
mockall  = {version = "0.12.1"}
multiaddr = {version = "0.18.1"}